<?php
/**
 * Created by kilo with IntelliJ IDEA on 2017/8/31 23:30.
 *
 */
namespace common\widgets;

use yii\bootstrap\Widget;

class ExcelWidget extends Widget{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

    public function getView()
    {
        return parent::getView(); // TODO: Change the autogenerated stub
    }
}