<?php
/**
 * Created by kilo with IntelliJ IDEA on 2017/8/24 21:52.
 *
 */
namespace backend\event;

use yii\base\Component;
use yii\base\Event;

class AlipayEvent extends Component {
    const EVENT_UPDATE = 'update';
    public function init()
    {
        $this->on(self::EVENT_UPDATE, [$this, 'update']);
//        $this->on(self::EVENT_NEW_USER, [$this, 'notification');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function update($array){
//        echo 'to do something';

        if(is_object($array)){
            echo 'this is a object 对象';
        }else{
            die('不是数组');
        }
    }
}