<?php
/**
 * Created by kilo with IntelliJ IDEA on 2017/8/24 23:24.
 *
 */
namespace backend\event;

/**
 * Class SendMessage
 * @package backend\event
 * 信息发送类
 */
class SendMessage{
//    public function init()
//    {
//        parent::init(); // TODO: Change the autogenerated stub
//    }

    public static function sendMessage($event){
//        var_dump($event);die();
        echo 'sendMessage to somebody'.'<br>';;
    }

    public static function sendNotice($event){
        echo 'sendMessage class send a notice gice you'.'<br>';
    }
}